http.host: "0.0.0.0"
http.port: 9600

pipeline.workers: 4
pipeline.batch.size: 500
pipeline.batch.delay: 50

queue.type: persisted
queue.max_bytes: 4gb

dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1gb

log.level: info
log.format: json
